<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\Table;
use Cake\Validation\Validator;

class CustomersTable extends Table
{
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('customers');
        $this->setPrimaryKey('id');
        $this->addBehavior('Timestamp');

        // Tell CakePHP the primary key is auto-generated by the database.
        // Without this, CakePHP may send id=0 on INSERT when the column
        // lacks AUTO_INCREMENT or when the sequence isn't wired up correctly,
        // causing "Duplicate entry '0' for key 'PRIMARY'".

        $this->hasMany('Devices', [
            'foreignKey' => 'customer_id',
        ]);
    }

    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->scalar('full_name')
            ->maxLength('full_name', 150)
            ->requirePresence('full_name', 'create');

        $validator
            ->scalar('contact_no')
            ->maxLength('contact_no', 20)
            ->allowEmptyString('contact_no');

        $validator
            ->scalar('phone_model')
            ->maxLength('phone_model', 100)
            ->allowEmptyString('phone_model');

        $validator
            ->scalar('phone_issue')
            ->allowEmptyString('phone_issue');

        $validator
            ->scalar('diagnostic')
            ->allowEmptyString('diagnostic');

        $validator
            ->scalar('suggested_part_replacement')
            ->allowEmptyString('suggested_part_replacement');

        $validator
            ->scalar('notes')
            ->allowEmptyString('notes');

        return $validator;
    }
}